# Generated by Django 5.0.4 on 2024-05-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('first_price', models.FloatField(max_length=200)),
                ('sale_price', models.FloatField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('reg_data', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('where_to', models.CharField(max_length=200)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
