# Generated by Django 5.0.4 on 2024-05-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_system', '0002_brand_filial_alter_product_brand_warehouse_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='background_img',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m'),
        ),
    ]
